export type BoardTemplate = {
  id: string;
  name: string;
  size: "small" | "regular" | "large";
  strip3Enabled: boolean;
  // Wood keys (no nulls per requirements)
  strips: string[][];
  order: { stripNo: number; reflected: boolean }[];
};

export const TEMPLATES: BoardTemplate[] = [
  {
    id: "classic-two-strip",
    name: "Classic Two Strip",
    size: "regular",
    strip3Enabled: false,
    strips: [
      // 12 cells per row for regular
      [
        "maple",
        "walnut",
        "maple",
        "walnut",
        "maple",
        "walnut",
        "maple",
        "walnut",
        "maple",
        "walnut",
        "maple",
        "walnut",
      ],
      [
        "walnut",
        "maple",
        "walnut",
        "maple",
        "walnut",
        "maple",
        "walnut",
        "maple",
        "walnut",
        "maple",
        "walnut",
        "maple",
      ],
      // third strip present but ignored when disabled
      [
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
      ],
    ],
    // 14 rows for regular (explicit)
    order: [
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
    ],
  },
  {
    id: "tri-tone",
    name: "Tri-Tone",
    size: "large",
    strip3Enabled: true,
    strips: [
      [
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
        "maple",
      ],
      [
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
        "walnut",
      ],
      [
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
        "purpleheart",
      ],
    ],
    // 16 rows for large (explicit)
    order: [
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: true },
      { stripNo: 3, reflected: false },
      { stripNo: 1, reflected: true },
      { stripNo: 2, reflected: false },
      { stripNo: 3, reflected: true },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: true },
      { stripNo: 3, reflected: false },
      { stripNo: 1, reflected: true },
      { stripNo: 2, reflected: false },
      { stripNo: 3, reflected: true },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: true },
      { stripNo: 3, reflected: false },
      { stripNo: 1, reflected: true },
    ],
  },
  {
    id: "power-stripe",
    name: "Power Stripe",
    size: "regular",
    strip3Enabled: false,
    strips: [
      [
        "cherry",
        "cherry",
        "cherry",
        "cherry",
        "cherry",
        "cherry",
        "padauk",
        "maple",
        "padauk",
        "cherry",
        "cherry",
        "cherry",
      ],
      [
        "cherry",
        "cherry",
        "cherry",
        "cherry",
        "cherry",
        "cherry",
        "maple",
        "padauk",
        "maple",
        "cherry",
        "cherry",
        "cherry",
      ],
    ],
    // 16 rows (explicit)
    order: [
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
      { stripNo: 1, reflected: false },
      { stripNo: 2, reflected: false },
    ],
  },
];

export const LS_SELECTED_TEMPLATE_KEY = "bb.selectedTemplate";
